#include "room_vars.h"

// created by myself
struct room admin_hall_r = { "Main Hall", "b000", {} };
struct room cafeteria_r = {"Cafeteria", "b008", { 0x0000025A00020401, 0x000000CA00020402, 0x0000026400020403} };
struct room infirmary_r = {"Infirmary", "e103", { 0x0000025A00053383, 0x0000025F00053386, 0x0000025F00053385, 0x0000025F00053384 } };
extern char *rooms_ids_str[] =
{
    "a000",
    "a001",
    "a002",
    "a003",
    "a004",

    "b000",
    "b002",
    "b004",
    "b005",
    "b006",
    "b007",
    "b008",
    "b009",
    "b010",
    "b100",
    "b102",
    "b103",
    "b104",
    "b106",

    "c000",
    "c003",
    "c004",
    "c006",
    "c009",
    "c010",
    "c011",
    "c100",
    "c101",
    "c104",
    "c105",
    "c109",

    "d000",
    "d001",
    "d002",
    "d003",
    "d004",
    "d005",
    "d006",
    "d009",
    "d010",
    "d100",
    "d101",
    "d102",
    "d103",
    "d104",
    "d105",
    "d106",

    "e000",
    "e001",
    "e002",
    "e003",
    "e100",
    "e101",
    "e102",
    "e103",

    "f000",
    "f001",
    "f002",
    "f003",
    "f101",
    "f102",

    "g000",
    "g001",
    "g002",
    "g003",
    "g004",
    "g005",
    "g006",
    "g007",
    "g008",
    "g009",
    "g010",
    "g012",
    "g013",
    "g014",
    "g015",
    "g016",
    "g100",
    "g103",
    "g104",
    "g105",
    "g106",
    "g107",

    "i000",
    "i001",
    "i002",
    "i004",
    "i007",
    "i100",
    "i101",
    "i102",
    "i103",
    "i107",

    "j000",
    "j001",

    "m000",
    "m001",
    "m002",
    "m003",
    "m100"
};

// generated by the program
struct room room0 = { "a000", "a000", { 0x000000D900010001 } };
struct room room1 = { "a001", "a001", { 0x0000025F00010082 } };
struct room room2 = { "a002", "a002", { 0x0000025A00010102, 0x0000025F00010103 } };
struct room room3 = { "a003", "a003", { 0x0000025F00010181, 0x0000026400010182, 0x0000026400010183 } };
struct room room4 = { "a004", "a004", { 0x000000CB00010201, 0x0000025B00010203, 0x0000025A00010204 } };
struct room room5 = { "b000", "b000", {  } };
struct room room6 = { "b002", "b002", { 0x0000025B00020132 } };
struct room room7 = { "b004", "b004", {  } };
struct room room8 = { "b005", "b005", { 0x0000025A00020281 } };
struct room room9 = { "b006", "b006", { 0x0000026400020301 } };
struct room room10 = { "b007", "b007", { 0x0000026400020381 } };
struct room room11 = { "b008", "b008", { 0x0000025A00020401, 0x000000CA00020402, 0x0000026400020403 } };
struct room room12 = { "b009", "b009", { 0x0000025F00020481 } };
struct room room13 = { "b010", "b010", {  } };
struct room room14 = { "b100", "b100", { 0x000000D100023201, 0x0000026400023202 } };
struct room room15 = { "b102", "b102", {  } };
struct room room16 = { "b103", "b103", { 0x0000025A00023382 } };
struct room room17 = { "b104", "b104", { 0x0000025A00023403 } };
struct room room18 = { "b106", "b106", { 0x0000025A00023503 } };
struct room room19 = { "c000", "c000", { 0x000000DA00030002, 0x0000026400030003, 0x0000026400030004 } };
struct room room20 = { "c003", "c003", { 0x0000025F00030181 } };
struct room room21 = { "c004", "c004", { 0x000000CB00030203 } };
struct room room22 = { "c006", "c006", { 0x0000025A00030301 } };
struct room room23 = { "c009", "c009", {  } };
struct room room24 = { "c010", "c010", { 0x0000025A00030503 } };
struct room room25 = { "c011", "c011", { 0x0000025B00030581 } };
struct room room26 = { "c100", "c100", { 0x0000025A00033202, 0x0000026400033203, 0x000000CB00033205 } };
struct room room27 = { "c101", "c101", {  } };
struct room room28 = { "c104", "c104", { 0x0000026400033401 } };
struct room room29 = { "c105", "c105", { 0x0000025A00033481, 0x0000026400033482, 0x0000025B00033483 } };
struct room room30 = { "c109", "c109", { 0x000000D300033681, 0x0000025A00033693, 0x000000DC00033694 } };
struct room room31 = { "d000", "d000", { 0x0000025A00040002 } };
struct room room32 = { "d001", "d001", { 0x0000025B00040081 } };
struct room room33 = { "d002", "d002", {  } };
struct room room34 = { "d003", "d003", { 0x0000025A0004018B } };
struct room room35 = { "d004", "d004", { 0x0000025A00040201 } };
struct room room36 = { "d005", "d005", { 0x0000026400040283 } };
struct room room37 = { "d006", "d006", { 0x0000026400040301 } };
struct room room38 = { "d009", "d009", {  } };
struct room room39 = { "d010", "d010", {  } };
struct room room40 = { "d100", "d100", { 0x0000025A00043201 } };
struct room room41 = { "d101", "d101", { 0x0000026400043281, 0x0000026400043282, 0x0000026400043283, 0x0000025A00043284 } };
struct room room42 = { "d102", "d102", { 0x000000D800043301 } };
struct room room43 = { "d103", "d103", { 0x0000025B00043381, 0x0000025F00043383 } };
struct room room44 = { "d104", "d104", { 0x0000025B00043401 } };
struct room room45 = { "d105", "d105", { 0x0000025F00043481 } };
struct room room46 = { "d106", "d106", { 0x0000025F00043502 } };
struct room room47 = { "e000", "e000", { 0x000000D700050003 } };
struct room room48 = { "e001", "e001", { 0x000000CE00050081 } };
struct room room49 = { "e002", "e002", { 0x0000026400050101, 0x0000025A00050102 } };
struct room room50 = { "e003", "e003", {  } };
struct room room51 = { "e100", "e100", { 0x0000026400053202, 0x0000026400053203, 0x0000025F00053204 } };
struct room room52 = { "e101", "e101", { 0x0000025A00053282, 0x0000025F00053281, 0x0000026400053283, 0x000000D700053284 } };
struct room room53 = { "e102", "e102", {  } };
struct room room54 = { "e103", "e103", { 0x0000025F00053384, 0x0000025F00053385, 0x0000025A00053383, 0x0000025F00053386 } };
struct room room55 = { "f000", "f000", { 0x0000025A00060002, 0x0000025B00060003 } };
struct room room56 = { "f001", "f001", { 0x0000025A00060082 } };
struct room room57 = { "f002", "f002", { 0x0000025F00060102 } };
struct room room58 = { "f003", "f003", { 0x0000025B00060183, 0x0000025F00060184 } };
struct room room59 = { "f101", "f101", { 0x0000026400063281, 0x0000025F00063282 } };
struct room room60 = { "f102", "f102", {  } };
struct room room61 = { "g000", "g000", { 0x0000026400070001 } };
struct room room62 = { "g001", "g001", { 0x0000025F00070083, 0x0000025A00070084 } };
struct room room63 = { "g002", "g002", { 0x000000CE00070101 } };
struct room room64 = { "g003", "g003", { 0x0000025F00070182 } };
struct room room65 = { "g004", "g004", {  } };
struct room room66 = { "g005", "g005", { 0x0000025A00070281, 0x0000026400070282, 0x0000025B00070283 } };
struct room room67 = { "g006", "g006", {  } };
struct room room68 = { "g007", "g007", { 0x0000025F00070381, 0x0000026400070382 } };
struct room room69 = { "g008", "g008", { 0x0000025F00070402, 0x0000025F00070403, 0x0000025A00070401 } };
struct room room70 = { "g009", "g009", {  } };
struct room room71 = { "g010", "g010", { 0x0000025A00070503, 0x0000025F00070501 } };
struct room room72 = { "g012", "g012", {  } };
struct room room73 = { "g013", "g013", { 0x0000025F00070682 } };
struct room room74 = { "g014", "g014", { 0x0000026400070701, 0x0000025F00070702 } };
struct room room75 = { "g015", "g015", {  } };
struct room room76 = { "g016", "g016", { 0x000000CB00070801 } };
struct room room77 = { "g100", "g100", {  } };
struct room room78 = { "g103", "g103", { 0x0000025F00073381 } };
struct room room79 = { "g104", "g104", { 0x0000025A00073401 } };
struct room room80 = { "g105", "g105", { 0x0000025F00073481 } };
struct room room81 = { "g106", "g106", {  } };
struct room room82 = { "g107", "g107", { 0x0000025A00073581 } };
struct room room83 = { "i000", "i000", { 0x0000026400090002 } };
struct room room84 = { "i001", "i001", { 0x0000025F00090085 } };
struct room room85 = { "i002", "i002", { 0x0000025A00090101 } };
struct room room86 = { "i004", "i004", { 0x0000025F00090201, 0x0000026400090202 } };
struct room room87 = { "i007", "i007", {  } };
struct room room88 = { "i100", "i100", { 0x0000025A00093202 } };
struct room room89 = { "i101", "i101", { 0x0000026400093284, 0x0000026400093283 } };
struct room room90 = { "i102", "i102", { 0x0000025A00093301 } };
struct room room91 = { "i103", "i103", {  } };
struct room room92 = { "i107", "i107", { 0x0000025F00093583 } };
struct room room93 = { "j000", "j000", {  } };
struct room room94 = { "j001", "j001", {  } };
struct room room95 = { "m000", "m000", { 0x0000025A000D0001 } };
struct room room96 = { "m001", "m001", { 0x0000025F000D0081 } };
struct room room97 = { "m002", "m002", { 0x0000025A000D0101, 0x0000025F000D0102 } };
struct room room98 = { "m003", "m003", {  } };
struct room room99 = { "m100", "m100", { 0x0000025A000D3201 } };

//struct room *rooms[] = { &admin_hall_r, &cafeteria_r, &infirmary_r };
//enum room_id rooms_ids[] = { B000, B008, E103 };
enum room_id rooms_ids[] =
{
        A000,
        A001,
        A002,
        A003,
        A004,
        B000,
        B002,
        B004,
        B005,
        B006,
        B007,
        B008,
        B009,
        B010,
        B100,
        B102,
        B103,
        B104,
        B106,
        C000,
        C003,
        C004,
        C006,
        C009,
        C010,
        C011,
        C100,
        C101,
        C104,
        C105,
        C109,
        D000,
        D001,
        D002,
        D003,
        D004,
        D005,
        D006,
        D009,
        D010,
        D100,
        D101,
        D102,
        D103,
        D104,
        D105,
        D106,
        E000,
        E001,
        E002,
        E003,
        E100,
        E101,
        E102,
        E103,
        F000,
        F001,
        F002,
        F003,
        F101,
        F102,
        G000,
        G001,
        G002,
        G003,
        G004,
        G005,
        G006,
        G007,
        G008,
        G009,
        G010,
        G012,
        G013,
        G014,
        G015,
        G016,
        G100,
        G103,
        G104,
        G105,
        G106,
        G107,
        I000,
        I001,
        I002,
        I004,
        I007,
        I100,
        I101,
        I102,
        I103,
        I107,
        J000,
        J001,
        M000,
        M001,
        M002,
        M003,
        M100,
};

struct room *rooms[] =
{
        &room0,
        &room1,
        &room2,
        &room3,
        &room4,
        &room5,
        &room6,
        &room7,
        &room8,
        &room9,
        &room10,
        &room11,
        &room12,
        &room13,
        &room14,
        &room15,
        &room16,
        &room17,
        &room18,
        &room19,
        &room20,
        &room21,
        &room22,
        &room23,
        &room24,
        &room25,
        &room26,
        &room27,
        &room28,
        &room29,
        &room30,
        &room31,
        &room32,
        &room33,
        &room34,
        &room35,
        &room36,
        &room37,
        &room38,
        &room39,
        &room40,
        &room41,
        &room42,
        &room43,
        &room44,
        &room45,
        &room46,
        &room47,
        &room48,
        &room49,
        &room50,
        &room51,
        &room52,
        &room53,
        &room54,
        &room55,
        &room56,
        &room57,
        &room58,
        &room59,
        &room60,
        &room61,
        &room62,
        &room63,
        &room64,
        &room65,
        &room66,
        &room67,
        &room68,
        &room69,
        &room70,
        &room71,
        &room72,
        &room73,
        &room74,
        &room75,
        &room76,
        &room77,
        &room78,
        &room79,
        &room80,
        &room81,
        &room82,
        &room83,
        &room84,
        &room85,
        &room86,
        &room87,
        &room88,
        &room89,
        &room90,
        &room91,
        &room92,
        &room93,
        &room94,
        &room95,
        &room96,
        &room97,
        &room98,
        &room99
};
